/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cards.briscola;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import cards.creaCarte;

/**
 *
 * @author user
 */
public class brisc extends javax.swing.JPanel {

    /**
     * Creates new form brisc
     */
    public brisc() {
        initComponents();
        System.out.println("due");
        this.setLayout(null);
        int i,n=40,brisc;
        JButton briscola;
        JButton mani[]=new JButton[6];
        JLabel lab[]=new JLabel[8];
        creaCarte c=new creaCarte(n);
        for(i=0;i<6;i++)
        {
            mani[i]=new JButton(disegna(c,(int)(Math.random()*n)));
            mani[i].setBounds(700*((i+1)%3), 700*(i/3), 200, 300);
            this.add(mani[i]);
            n=-1;
        }
        brisc=(int)(Math.random()*n);
        n=-1;
        briscola=new JButton(disegna(c,brisc));
        brisc=brisc/10+1;
        System.out.println(brisc);
        briscola.setBounds(700,350,200,300);
        this.add(briscola);
    }
    public ImageIcon disegna(creaCarte c,int n)
    {
        ImageIcon t= c.getCard(n).get();
        return t;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
